---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch:
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  commands:
  - bash build.sh
  
- uses: actions/upload-artifact@v2
  with:
  name: recoveryzip
  path: twrp11/out/target/product/*/*.zip

- uses: actions/upload-artifact@v2
  with:
  name: recoveryimage
  path: twrp11/out/target/product/*/*.img
